### ISSUE TITLE
Special characters in Redis Keys

### ISSUE THREAD

**Issue by rinshadka** [postalsys/imapapi#79]
Hi @andris9 

I have tried registering a gmail account named "**imapapi123**" using API and found below Redis Keys using redis-cli,

```
iad:imapapi123
ial:imapapi123
```

I was able to access "**iad:imapapi123**" Key like below,

![2021-07-28 21_21_49-redis-cli](https://user-images.githubusercontent.com/40381766/127356717-cf3d5a7f-2cab-485e-a2a5-ed46d50b237d.png)

But while checking the values in the "**ial:imapapi123**" Key, I found few special characters.

![2021-07-28 21_22_19-redis-cli](https://user-images.githubusercontent.com/40381766/127356912-00da67ab-0d90-4aff-a958-e5c08987a00e.png)

Is there any character encoding in place?  Actually I wanted to read the Redis database directly.

Thanks.

**Comment by andris9** [comment]
This is MessagePack format: https://msgpack.org/ so read the value from Redis as a Buffer not String and then use a messagepack decoder on it to
